#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.l_imgPrimary = QtWidgets.QLabel(self.centralwidget)
        self.l_imgPrimary.setGeometry(QtCore.QRect(30, 50, 260, 320))
        self.l_imgPrimary.setObjectName("l_imgPrimary")
        self.l_imgProcess = QtWidgets.QLabel(self.centralwidget)
        self.l_imgProcess.setGeometry(QtCore.QRect(340, 50, 260, 320))
        self.l_imgProcess.setObjectName("l_imgProcess")
        self.e_areaPredict = QtWidgets.QLineEdit(self.centralwidget)
        self.e_areaPredict.setGeometry(QtCore.QRect(520, 440, 81, 20))
        self.e_areaPredict.setObjectName("e_areaPredict")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(440, 440, 71, 21))
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(440, 400, 71, 16))
        self.label_2.setObjectName("label_2")
        self.e_areaDetect = QtWidgets.QLineEdit(self.centralwidget)
        self.e_areaDetect.setGeometry(QtCore.QRect(520, 400, 81, 21))
        self.e_areaDetect.setReadOnly(True)
        self.e_areaDetect.setObjectName("e_areaDetect")
        self.b_readImg = QtWidgets.QPushButton(self.centralwidget)
        self.b_readImg.setGeometry(QtCore.QRect(30, 460, 141, 41))
        self.b_readImg.setObjectName("b_readImg")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(440, 480, 71, 21))
        self.label_3.setObjectName("label_3")
        self.e_valueDetect = QtWidgets.QLineEdit(self.centralwidget)
        self.e_valueDetect.setGeometry(QtCore.QRect(520, 480, 81, 21))
        self.e_valueDetect.setReadOnly(True)
        self.e_valueDetect.setObjectName("e_valueDetect")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 400, 75, 21))
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setObjectName("label_4")
        self.e_imgPath = QtWidgets.QLineEdit(self.centralwidget)
        self.e_imgPath.setGeometry(QtCore.QRect(30, 420, 141, 21))
        self.e_imgPath.setObjectName("e_imgPath")
        self.b_nextImg = QtWidgets.QPushButton(self.centralwidget)
        self.b_nextImg.setGeometry(QtCore.QRect(240, 460, 141, 41))
        self.b_nextImg.setObjectName("b_nextImg")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 71, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 20, 81, 21))
        self.label_6.setObjectName("label_6")
        self.b_prevImg = QtWidgets.QPushButton(self.centralwidget)
        self.b_prevImg.setGeometry(QtCore.QRect(240, 400, 141, 41))
        self.b_prevImg.setObjectName("b_prevImg")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l_imgPrimary.setText(_translate("MainWindow", "TextLabel"))
        self.l_imgProcess.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "预测面积："))
        self.label_2.setText(_translate("MainWindow", "实际面积："))
        self.b_readImg.setText(_translate("MainWindow", "开始读取"))
        self.label_3.setText(_translate("MainWindow", "检测结果："))
        self.label_4.setText(_translate("MainWindow", "图片路径："))
        self.b_nextImg.setText(_translate("MainWindow", "下一张"))
        self.label_5.setText(_translate("MainWindow", "原始图片："))
        self.label_6.setText(_translate("MainWindow", "处理后图片："))
        self.b_prevImg.setText(_translate("MainWindow", "前一张"))
